name: Add a comment on new open issues

on:
  issues:
    types:
      - opened
jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "greet new issue"
        run: echo '${{ toJSON(github.event)}}' | jq
        shell: bash
